---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache-pulsar
  name: apache-pulsar
spec:
  ports:
    - port: 6650
      name: pulsar-port
      protocol: TCP
      targetPort: 6650
    - port: 8080
      name: http-port
      protocol: TCP
      targetPort: 8080
  selector:
    app: apache-pulsar

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: apache-pulsar
  name: apache-pulsar
spec:
  selector:
    matchLabels:
      app: apache-pulsar
  serviceName: apache-pulsar
  template:
    metadata:
      labels:
        app: apache-pulsar
    spec:
      volumes:
        - name: pulsardata
          emptyDir: {}
      containers:
        - name: apache-pulsar
          image: apachepulsar/pulsar:3.1.1
          command:
            - bin/pulsar
            - standalone
          ports:
            - containerPort: 6650
            - containerPort: 8080
          volumeMounts:
            - mountPath: /pulsar/data
              name: pulsardata
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 10