apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache-pulsar
  name: apache-pulsar
spec:
  ports:
    - port: 6650
      protocol: TCP
      targetPort: 6650
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: apache-pulsar
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: apache-pulsar
  name: apache-pulsar
spec:
  selector:
    matchLabels:
      app: apache-pulsar
  serviceName: apache-pulsar
  template:
    metadata:
      labels:
        app: apache-pulsar
    spec:
      containers:
        - name: moto
          command: [ "bin/pulsar", "standalone"]
          image: apachepulsar/pulsar:3.1.1
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 10
          ports:
            - containerPort: 5000
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 10